In [3]:
import pandas as pd 
df = pd.read_csv('/Users/jw/python/4.Study/data/auto-mpg.csv', header=None)
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'name']

In [4]:
print(df['horsepower'])
print(df['displacement'])

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393    86.00
394    52.00
395    84.00
396    79.00
397    82.00
Name: horsepower, Length: 398, dtype: object
0      307.0
1      350.0
2      318.0
3      304.0
4      302.0
       ...  
393    140.0
394     97.0
395    135.0
396    120.0
397    119.0
Name: displacement, Length: 398, dtype: float64


In [5]:
# displacement를 초대형, 대형, 중형, 준중형, 소형 으로 새로운 컬럼 만들기

# 5등분할 숫자 배열 만들기 
import numpy as np 

count, bin_dividers = np.histogram(df['displacement'], bins=5)
print(bin_dividers)

[ 68.  145.4 222.8 300.2 377.6 455. ]


In [6]:
# 치환할 데이터 배열 만들기 
bin_names = ['소형', '준중형','중형', '대형', '초대형']

# 치환 
df['차량분류'] = pd.cut( x= df['displacement'], bins=bin_dividers, labels=bin_names, include_lowest= True)
print(df)

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0      130.0  3504.0          12.0   
1    15.0          8         350.0      165.0  3693.0          11.5   
2    18.0          8         318.0      150.0  3436.0          11.0   
3    16.0          8         304.0      150.0  3433.0          12.0   
4    17.0          8         302.0      140.0  3449.0          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0      86.00  2790.0          15.6   
394  44.0          4          97.0      52.00  2130.0          24.6   
395  32.0          4         135.0      84.00  2295.0          11.6   
396  28.0          4         120.0      79.00  2625.0          18.6   
397  31.0          4         119.0      82.00  2720.0          19.4   

     model year  origin                       name 차량분류  
0            70       1  chevrolet chevelle malibu   대형  
1            70       1          buic

In [9]:
# numpy digitze 이용 
age = np.array([[30], [40], [29], [50], [60]])
# 40을 기준으로 분할 - 경계값이 다음 그룹으로 분할
print(np.digitize(age, bins=[40]))
print()
print(np.digitize(age, bins=[30, 50]))
print()
# right를 이용하면 경계값이 아래 그룹으로 분할
print(np.digitize(age, bins=[30, 50], right=True))

[[0]
 [1]
 [0]
 [1]
 [1]]

[[1]
 [1]
 [0]
 [2]
 [2]]

[[0]
 [1]
 [0]
 [1]
 [2]]


In [10]:
# 여러 개의 열로 구성된 데이터의 이산화 
sample = np.array([[20,30],[40,70],[30, 60],[25,34],[43,75],[38, 63]])
df = pd.DataFrame(sample)
print(df)

0   1
0  20  30
1  40  70
2  30  60
3  25  34
4  43  75
5  38  63


In [12]:
# KMeans 군집 분석을 위한 라이브러리 
from sklearn.cluster import KMeans
# 군집분석 객체 생성
cluster = KMeans(3, random_state=0)
# 데이터를 가지고 훈련 
cluster.fit(sample)
# 예측 - 군집 
df['group'] = cluster.predict(sample)
print(df)

0   1  group
0  20  30      1
1  40  70      0
2  30  60      2
3  25  34      1
4  43  75      0
5  38  63      2
