In [46]:
import random

li = list(range(1, 49, 1))
print(li)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]


In [47]:
# 랜덤하게 섞음 
random.shuffle(li)
print(li)

[3, 42, 43, 41, 27, 7, 8, 20, 6, 14, 39, 22, 2, 35, 4, 12, 46, 18, 36, 13, 26, 31, 29, 25, 30, 23, 15, 44, 37, 47, 24, 17, 48, 34, 21, 5, 11, 16, 45, 9, 32, 38, 28, 19, 1, 10, 40, 33]


In [48]:
# 비복원 추출
print(random.sample(li, k=4))

[38, 2, 15, 48]


In [49]:
import numpy as np 
li = ['라투', '오미크론', '다크스펙터', '나이즈']
print(np.random.choice(li, 4))  # 동일한 비율로 추출
print(np.random.choice(li, 4, p=[0.05, 0.3, 0.15, 0.5]))   # 설정된 비율로 추출 


['나이즈' '라투' '다크스펙터' '나이즈']
['오미크론' '나이즈' '오미크론' '나이즈']


In [50]:
# 행렬 생성
# 독립변수는 X로 표현을 많이 한다. 
X = np.arange(20).reshape(10, 2)
print(X)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [51]:
# 종족변수는 y로 표현을 많이 합니다. 
# 독립변수에 의해 값이 결정되는 것이 종속변수 
# 분류를 할 때는 분류될 클래스가 종속 변수 
y = np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
# 성별(sex) 과 나이(age)를 가지고 생존여부(survived)를 예측
# sex, age를 묶어서 X로 생성 survived가 y 

# X와 y에서 훈련 데이터와 시험 데이터를 분할 
# 훈련 데이터는 예측할 모델을 만들기 위한 데이터이고, 
# 시험 데이터는 만들어진 모델을 검증하기 위한 데이터이다. 
# 7:3 이나 8:2를 주로 이용 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=False, random_state = 1004) 
print(X_train)
print(y_train)
# shuffle=True 로 하면 섞여서 나옴

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
[0 1 2 3 4 5 6]


In [53]:
# 층화 무작위 추출
# 계층의 비율을 적용해서 데이터를 샘플링
z = [0,0,0,1,1,1,1,1,1,1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1008, stratify=z) 
print(X_train)
print(y_train)

[[10 11]
 [ 6  7]
 [16 17]
 [ 2  3]
 [14 15]
 [ 4  5]
 [18 19]]
[5 3 8 1 7 2 9]
