In [10]:
import platform
from matplotlib import font_manager, rc
import numpy as np 
import pandas as pd

df = pd.read_csv('/Users/jw/python/4.Study/data/student.csv', encoding='cp949', index_col='이름')

# 그래프의 한글 깨짐
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(
        fname="c:/Windows/Fonts/malgun.ttf").get_name()
    rc('font', family=font_name)

In [11]:
# 2차원 행렬을 생성
matrix = df[['국어', '영어']].values
print(matrix)
print()
matrix = np.array([[30,20], [10, 30], [30,40]])
print(matrix)

[[90 85]
 [70 65]
 [92 95]
 [76 89]
 [97 87]
 [80 86]
 [20 30]
 [50 52]
 [95 70]]

[[30 20]
 [10 30]
 [30 40]]


In [12]:
from sklearn import preprocessing

# 정규화 객체 생성 - 유클리디안 거리를 사용
norm = preprocessing.Normalizer(norm='l2')
print(norm.transform(matrix))

[[0.83205029 0.5547002 ]
 [0.31622777 0.9486833 ]
 [0.6        0.8       ]]


In [13]:
# 맨하턴 거리 (결과는 합치면 1)
norm = preprocessing.Normalizer(norm='l1')
print(norm.transform(matrix))

[[0.6        0.4       ]
 [0.25       0.75      ]
 [0.42857143 0.57142857]]


In [14]:
# max
norm = preprocessing.Normalizer(norm='max')
print(norm.transform(matrix))

[[1.         0.66666667]
 [0.33333333 1.        ]
 [0.75       1.        ]]


In [15]:
# 다항과 교차항을 만들어주는 객체를 생성
# degree=2 : 제곱한 것 까지 생성 
ploynomial = preprocessing.PolynomialFeatures(degree=2, include_bias=False)
result = ploynomial.fit_transform(matrix)
print(result)

[[  30.   20.  900.  600.  400.]
 [  10.   30.  100.  300.  900.]
 [  30.   40.  900. 1200. 1600.]]


In [16]:
# degree=3 : 세제곱
ploynomial = preprocessing.PolynomialFeatures(degree=3, include_bias=False)
result = ploynomial.fit_transform(matrix)
print(result)

[[3.0e+01 2.0e+01 9.0e+02 6.0e+02 4.0e+02 2.7e+04 1.8e+04 1.2e+04 8.0e+03]
 [1.0e+01 3.0e+01 1.0e+02 3.0e+02 9.0e+02 1.0e+03 3.0e+03 9.0e+03 2.7e+04]
 [3.0e+01 4.0e+01 9.0e+02 1.2e+03 1.6e+03 2.7e+04 3.6e+04 4.8e+04 6.4e+04]]


In [17]:
# 함수 적용하기 
matrix = np.array([[100, 200],[300, 150]])
print(matrix)

[[100 200]
 [300 150]]


In [18]:
# 100을 결합하기  
def intconvert(x) : 
    return x +100

transformer = preprocessing.FunctionTransformer(intconvert)
result = transformer.transform(matrix)
print(result)

[[200 300]
 [400 250]]


In [19]:
print(df['국어'])
print(df['국어'].apply(intconvert))

이름
박지영    90
김태함    70
김효섭    92
임경희    76
권혁진    97
하혜진    80
이준원    20
윤정웅    50
주시현    95
Name: 국어, dtype: int64
이름
박지영    190
김태함    170
김효섭    192
임경희    176
권혁진    197
하혜진    180
이준원    120
윤정웅    150
주시현    195
Name: 국어, dtype: int64
