In [41]:
import numpy as np

# 2차원 배열
ar = np.array([[100, 200, 300], [400, 500, 600]])
print(ar)

[[100 200 300]
 [400 500 600]]


In [42]:
# 서로 다른 자료형의 데이터가 모여 있으면 동일한 자료형으로 변경
ar = np.array([['100', 200, 300], [400, 500, 600]])
print(ar)

[['100' '200' '300']
 ['400' '500' '600']]


In [43]:
# dtype을 설정해서 정수 배열로 만들기
ar = np.array([['100', 200, 300], [400, 500, 600]], dtype=int)
print(ar)

[[100 200 300]
 [400 500 600]]


In [44]:
print(ar.ndim)  # 전체 차원을 리턴 결과값 : 2차원이다.
print(ar.shape)  # 각 차원의 데이터 개수를 튜플로 리턴 결과값 : (2, 3) # 2행3열이다

2
(2, 3)


In [45]:
# 일정한 숫자 패턴의 array 생성
ar = np.arange(0, 100, 1)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [46]:
#linspace는 기본적으로 stop이 포함됨
#마지막 숫자를 제거하고자 하면 endpoint를 False로 설정
ar = np.linspace(0, 10, num=10)
print(ar)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [47]:
# 단위 행렬 만들기 ( 대각선 방향의 요소만 1인 행렬) 
# 정방행렬 - 행과 열의 개수가 같은 행렬 
# 단위행렬 - 정방행렬이여야 한다. 

# 크기가 3인 단위 행렬 생성 
ar = np.eye(3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
# 1의 위치를 1개 증가
ar = np.eye(3, k=1)
print(ar)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [49]:
# 대각 요소만 뽑아서 1차원 배열을 생성 
ar = np.diag(ar) 
print(ar)

[0. 0. 0.]


In [50]:
# 희소행렬과 밀집행렬 변환 
# scipy 의 sparse 모듈 가져오기 
from scipy import sparse

# 5 * 5 단위 행렬 생성 
ar = np.eye(5) 
print(ar) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [51]:
# 희소행렬로 변환 - 0이 아닌 값의 위치와 값을 저장 
sp = sparse.csr_matrix(ar)
print(sp)

(0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0


In [52]:
# 밀집행렬로 변환 - 원래대로 돌리기 
ar = sp.toarray()
print(ar)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
# 행렬의 차원 변환
# 0 ~ 9 까지 10개의 요소로 된 1차원 배열 생성
ar = np.arange(0, 10)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
# 인덱싱과 copy
ar = np.array([100, 200, 300, 400])

# 0 ~ 1번까지 요소를 br에 링크를 전달 
br = ar[0:2]
print(br)

[100 200]


In [55]:
# 데이터를 복사해서 전달
cr = ar[0:2].copy()
print(cr)

[100 200]


In [56]:
#원본을 변경하면 br은 변경되지만 cr은 변경안됨.
#원본 데이터 변경
ar[0] = 10000
print(br)
print(cr)

[10000   200]
[100 200]


In [57]:
#쓰레기 값을 가지고 배열을 생성
ar = np.empty((10, 3))
print(ar)


[[ 9.00000000e+001  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  9.30537467e+199  1.49166815e-154]
 [ 1.49166815e-154  6.39828702e+170  1.46285969e-047]
 [ 4.26599394e-096  8.37170584e-144  5.88728849e-091]
 [ 1.38401414e-047  1.31452016e-047  5.74020278e+180]
 [ 8.37174974e-144  2.65532959e-312  1.49166815e-154]
 [-1.49458090e-154  5.43472210e-323  0.00000000e+000]]


In [58]:
# 행들을 선택 - 0, 1, 3, 5를 선택 - copy
br = ar[[0, 1, 3, 5]]
print(br)

[[9.00000000e+001 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.49166815e-154 6.39828702e+170 1.46285969e-047]]


In [59]:
# 현재는 같은 값을 가지고 있음
print(ar[0,0])
print(br[0,0])

90.0
90.0


In [60]:
# copy가 되었으므로 ar의 데이터가 변경되더라도 br이 데이터는 영향을 받지 않음
ar[0,0] = 90
print(ar[0,0])
print(br[0,0])

90.0
90.0


In [61]:
# 3, 5 행과 0, 2 열의 데이터를 추출 
cr = ar[[3, 5], [0,2]]  # 3,0 과 5,2만 추출
print(cr)

[0.00000000e+00 1.46285969e-47]


In [62]:
dr = ar[np.ix_([3, 5],[0, 2])] # 3,5행 0,2열 선택 
print(dr)

[[0.00000000e+000 0.00000000e+000]
 [1.49166815e-154 1.46285969e-047]]


In [63]:
# 행과 열의 순서 변경
ar = np.arange(0, 16) 
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [64]:
# 2차원 배열로 변환
br = ar.reshape(4, 4) 
print(br)
# 행렬 변환 - 2차원은 T나 transpose 가 동일 (3차원일때 차이가 있음) 
print(br.T)
print(br.transpose())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [65]:
# 3차원으로 변환
cr = ar.reshape((2, 2, 4))
print(cr) 
# 4, 2, 2 로 변경 
print(cr.transpose())
# 2, 4, 2 로 변경  
print(cr.transpose(0, 2, 1))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [66]:
# 배열이 모든 요소에게 함수를 적용해서 새로운 배열 만들기 
ar = np.arange(0, 5) 
print(ar)

[0 1 2 3 4]


In [67]:
#위의 배열에 전부 5를 더한 결과를 가지고 새로운 배열을 생성 
def plus5(x) :
    return x + 5 

# 벡터화된 함수를 생성
vec_func = np.vectorize(plus5)
print(vec_func(ar))

[5 6 7 8 9]


In [68]:
# 람다 함수 이용 
vec_func = np.vectorize(lambda x: x + 5)

#벡터화된 함수를 적용
result = vec_func(ar)
print(result)

[5 6 7 8 9]


In [69]:
#ndarray 가진 속성과 메소드 확인
print(dir(np.ndarray))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [70]:
# 동일한 자원의 동일한 크기의 배열 연산 
# 각 요소마다 연산해서 동일한 크기의 배열로 리턴 

ar = np.arange(0, 5)
br = np.linspace(100, 105, num=5, endpoint=False) # 100부터 105 까지 5개로 분할하는데 마지막 숫자는 미포함 
print(ar)
print(br) 

[0 1 2 3 4]
[100. 101. 102. 103. 104.]


In [71]:
result = ar + br    # 덧셈 , 숫자배열
print(result) 
result = ar > br    # 크기비교 , bool 배열 
print(result)
result = np.logical_xor(ar, br) # 논리연산 - 0 이 아닌 숫자는 True
print(result)

[100. 102. 104. 106. 108.]
[False False False False False]
[ True False False False False]


In [72]:
# 차원이 다른 배열의 연산 - Broadcast 
ar = np.array([100, 200, 500])
# 배열의 각 요소에서 100을 뺀 후 배열로 리턴 
result = ar - 100
print(result)

[  0 100 400]


In [73]:
br = np.arange(0, 6) 
cr = br.reshape(2, 3) 
print(cr) 

result = ar + cr
print(result)

[[0 1 2]
 [3 4 5]]
[[100 201 502]
 [103 204 505]]


In [74]:
# # 배열 크기가 달라서 계산 불가
# br = br.reshape(3, 2) 
# result = ar + dr
# print(result) 

In [75]:
# boolean 색인
ar = np.array([100, 200, 301, 28])
print(ar % 2 == 0)
# 배열의 인덱스 자리에 bool 배열을 대입하면 True인 데이터만 리턴 
print(ar[ar % 2 == 0])

[ True  True False  True]
[100 200  28]


In [76]:
# 난수 생성
# 배열 생성
ar = np.arange(0, 48)
np.random.shuffle(ar)   # 배열의 데이터 순서를 랜덤하게 배치
print(ar)
print()
print(np.random.normal(size=5))  # 5개의 랜덤한 숫자를 추출
print()
# seed 고정한 상태로 5개의 랜덤한 숫자를 추출 - 동일한값 출력 
np.random.seed(seed=100)  # seed 고정 
print(np.random.normal(size=5))
print()
print(np.random.normal(size=5))

[10 33 20 35 18 11 45 34  5 44  8  0 21 12  6 38 26 30 25 40 28 24 37 46
 43 47 32 23 14 39 15 17  7  3 42 41 36 19 13  1 31  4 27  2 22 29  9 16]

[ 1.37700072 -1.18738682  0.07939305  0.10796863  0.5069511 ]

[-1.74976547  0.3426804   1.1530358  -0.25243604  0.98132079]

[ 0.51421884  0.22117967 -1.07004333 -0.18949583  0.25500144]


In [77]:
# 기본 통계 함수 
ar = np.arange(1, 10)
ar = ar.reshape(3, 3)
print(ar) 
print()
print(np.sum(ar))   # 모든 데이터를 더한 결과
print()
# axis 옵션은 차후로도 동일한 용도로 사용되므로 기억 
print(np.sum(ar, axis=0))  # 열 단위 합계 
print(np.sum(ar, axis=1))  # 행 단위 함계

[[1 2 3]
 [4 5 6]
 [7 8 9]]

45

[12 15 18]
[ 6 15 24]


In [78]:
# 2개의 배열에서 데이터 골라서 새로운 배열 만들기
ar = np.array([100, 200, 300, 400])
br = np.array([101, 201, 301, 401])
cond = np.array([True, False, False, True])

result = np.where(cond, ar, br) #cond 값이 True면 ar에서, False 이면 br에서 추출 
print(result)

[100 201 301 400]


In [79]:
#데이터 정렬
ar = np.array([40, 200, 10, 100, 500,80])
result = np.sort(ar) 
print(result)
print()

br = ar.reshape(2, 3)
print(br)
print()

br.sort(axis=1)
print(br)

[ 10  40  80 100 200 500]

[[ 40 200  10]
 [100 500  80]]

[[ 10  40 200]
 [ 80 100 500]]


In [80]:
#일련 번호 형태로 배열만들기 
ar = np.arange(1, 13)

#3행 4열로 변경
ar = ar.reshape(3, 4) 

# 일정한 간격을 가지고 만들기 
br = np.linspace(101, 112, num=12)
br= br.reshape(3, 4) 
# 행 방향으로 합치기 
print(np.hstack([ar, br]))
print()
# 열 방향으로 합치기 
print(np.vstack([ar, br]))

[[  1.   2.   3.   4. 101. 102. 103. 104.]
 [  5.   6.   7.   8. 105. 106. 107. 108.]
 [  9.  10.  11.  12. 109. 110. 111. 112.]]

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [101. 102. 103. 104.]
 [105. 106. 107. 108.]
 [109. 110. 111. 112.]]
