In [11]:
import numpy as np 
import pandas as pd

# array를 입력받아서 z 점수(평균의 표준편차3범위) 밖에 있는 데이터를 리턴해주는 함수
def z_score_outlier(ar) : 
    threshold = 3
    # 평균가져오기
    meandata = np.mean(ar)
    stdevdata =  np.std(ar)
    # ar의 요소를 y에 하나씩 대입하고 앞에 수식을 적용해서 결과를 가지고 다시 list를 만드는것 
    z_scores = [(y-meandata) / stdevdata for y in ar]
    return np.where(np.abs(z_scores) > threshold)

# 샘플 데이터 생성
featrues = np.array([
                    [10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 2330, 
                    5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 
                    20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 
                    13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4], 
                    [10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 
                    4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -3440, 4,10, 13, 20, 5, -30, 
                    4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 4,10, 13, 20, 5, -30, 
                    4,10, 13, 20, 5, -30, 4]])
result = z_score_outlier(featrues)
print(result)
# 데이터가 적으면 출력값(참고) : (array([1]), array([5])) # 2행 6열이 이상치이다.
# 데이터가 많을때 출력값(참고) : (array([0, 1]), array([32, 64]))

(array([0, 1]), array([32, 64]))


In [12]:
# z score 보정 - 범위를 3.5배로 늘리고 표준편차 0.6875를 곱해준다. 
def modify_z_score_outlier(ar) : 
    threshold = 3.5
    # 평균가져오기
    meandata = np.mean(ar)
    stdevdata =  np.std(ar) 
    z_scores = [0.6875 * (y-meandata) / stdevdata for y in ar]
    return np.where(np.abs(z_scores) > threshold)

result = modify_z_score_outlier(featrues)
print(result)

(array([0, 1]), array([32, 64]))


In [13]:
# IQR 이용 : 3사분위수 - 1사분위수의 +- 1.5 배 이상 차이나면 이상치로 간주
def iqr_outlier(ar) : 
    # 25% 와 75% 값 찾기 
    q1, q3 = np.percentile(ar,[25,75])
    print(q1, q3)
    # IQR 값 찾기 
    iqr = q3 - q1 
    # 25% 값과 1.5 iqr 보다 작은 값 찾기 
    lower = q1 - iqr * 1.5
    upper = q3 + iqr * 1.5
    return np.where((ar > upper) | (ar < lower))

result = iqr_outlier(featrues)
print(result)

4.0 13.0
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([  4,  10,  16,  22,  28,  32,  34,  40,  46,  52,  58,  64,  70,
        76,  82,  88,  94, 100, 106, 112,   4,  10,  16,  22,  28,  34,
        40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106, 112]))
